# Generated by Django 3.2.13 on 2022-05-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=10, verbose_name='auth_token')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors_app.user')),
            ],
        ),
    ]
